# Generated by Django 4.0.6 on 2022-12-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('token', models.CharField(max_length=200)),
                ('headers', models.JSONField()),
            ],
        ),
    ]
